[package]
name = "rjest-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "rjest"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
rjest-config = { path = "../rjest-config" }
rjest-core = { path = "../rjest-core" }
rjest-coverage = { path = "../rjest-coverage" }
rjest-discovery = { path = "../rjest-discovery" }
rjest-runner = { path = "../rjest-runner" }
serde_json.workspace = true
sha1.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
