[package]
name = "rjest-runner"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
rayon.workspace = true
rjest-core = { path = "../rjest-core" }
rjest-snapshot = { path = "../rjest-snapshot" }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true

[lints]
workspace = true
